version: '3.4'

services:
  tictactoe.api:
    image: ${DOCKER_REGISTRY-}tictactoeapi
    container_name: "tictactoe.api"
    build:
      context: ./TicTacToe.Api
      dockerfile: TicTacToe.Api/Dockerfile
    ports:
      - "33000:80"
      - "33001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=tictactoe.db;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    volumes:
      - .:/user/src/app
    depends_on:
      - "tictactoe.db"

  tictactoe.db:
    restart: on-failure
    image: "mdillon/postgis:11"
    container_name: "tictactoe.db"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - tictactoe-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  tictactoe-db:
